=== sonit33/aarya/.schema/post-manifest-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"post_file": {
			"type": "string"
		},
		"post_title": {
			"type": "string"
		},
		"tags": {
			"type": "array",
			"items": {
				"type": "integer"
			}
		},
		"authors": {
			"type": "array",
			"items": {
				"type": "integer"
			}
		},
		"display_date": {
			"type": "string",
			"format": "date"
		},
		"description": {
			"type": "string"
		},
		"tldr": {
			"type": "string"
		},
		"keywords": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"subtitle": {
			"type": "string"
		}
	},
	"required": [
		"post_file",
		"post_title",
		"tags",
		"authors",
		"display_date",
		"description",
		"tldr",
		"keywords",
		"subtitle"
	]
}

=== sonit33/aarya/blog_app/manifests/2024-01-15-some-random-post.json
{
	"post_file": "posts/2024-01-15-some-random-post.md",
	"post_title": "Making sense of the AP Computer Science A exam format",
	"tags": [1],
	"authors": [34557],
	"display_date": "2024-01-15",
	"description": "This is an example post description.",
	"tldr": "TL;DR: Example TL;DR summary.",
	"keywords": ["example", "post", "keywords"],
	"subtitle": "Example Post Subtitle"
}
